# Systems/CrotchCode/CrotchTranspiler.gd
class_name CrotchTranspiler extends RefCounted

## Migrated from CrotchBlocks.gd (280 lines) and CodeContex.gd execution logic.
## Transpiles visual block graph into native GDScript 2.0 code.

const HEADER := """# GENERATED BY CROTCHCODE TRANSPILER
# Block count: %d
extends CrotchScriptBase

func execute() -> void:
"""

# Block type constants (migrated from CrotchBlocks.gd lines 4-7)
const CALL: int = 0
const VALUE: int = 1
const LOGIC: int = 2
const RETURNCALL: int = 3

# All block types (migrated from CrotchBlocks.gd getAll(), 170+ blocks)
const BLOCK_TYPES: Array[StringName] = [
	# Flow control
	&"FlowIf", &"FlowIfElse", &"FlowWhile",
	# Math
	&"MathPlus", &"MathMinus", &"MathMult", &"MathDivide", &"MathFMod", &"MathMod", &"MathPow",
	# Logic
	&"LogicAnd", &"LogicOr", &"LogicNot",
	&"MathLogicEquals", &"MathLogicNotEquals", &"MathLogicBiggerThan", &"MathLogicLessThan",
	&"MathLogicBiggerThanOrEq", &"MathLogicLessThanOrEq",
	# Scene
	&"SceneOutput", &"SceneSay", &"SceneButton", &"SceneButtonDisabled",
	&"SceneAimCamera", &"ScenePlayAnim", &"SceneCharAdd", &"SceneCharRem",
	&"SceneSetState", &"SceneGetState", &"SceneEndScene", &"SceneRunScene",
	&"SceneStartFight", &"SceneStartSex", &"SceneStartLeashParade",
	&"SceneAddMessage", &"SceneSetLocName", &"SceneImage", &"SceneRunOnce",
	# Quest
	&"QuestStage", &"QuestMarkAsVisible", &"QuestMarkAsCompleted",
	# Lewd
	&"LewdFuck", &"LewdOrgasmFrom", &"LewdCummedOnBy", &"LewdCumInside",
	&"LewdRubVaginas", &"LewdHasX", &"LewdGetX", &"LewdIsLactating",
	&"LewdIsPregnant", &"LewdIsWearing", &"LewdForceHeat", &"LewdMilk",
	&"LewdWriting", &"LewdIsCoveredIn", &"LewdHasBodypart", &"LewdBodypartHasTrait",
	&"LewdIsBodypartCovered", &"LewdClearFluids", &"LewdDamageClothes",
	&"LewdDoStretchHole", &"LewdDoStretchPain", &"LewdStraponButtons",
	&"LewdReturnStrapon", &"LewdAddFilledCondom", &"LewdGiveBirth",
	&"LewdGetChildAmount", &"LewdGetSharedChildAmount", &"LewdBreastFeed",
	&"LewdForceImpregnate", &"LewdShouldCondomBreak", &"LewdUseCondom",
	# Game
	&"GameProcessTime", &"GameAddAtr", &"GameGetAtr", &"GameGetStat",
	&"GameHasPerk", &"GameHasEffect", &"GameAddEffect", &"GameRemoveEffect",
	&"GameHasBuff", &"GameGetSkillLevel", &"GameAddSkillExp",
	&"GameAddPCAtr", &"GameGetPCAtr", &"GameSetPCLocation", &"GameIsPCInLocation",
	&"GameLocName", &"GameDoWound", &"GameCharExists", &"GameIsContentEnabled",
	&"GameGetDays", &"GameGetTime", &"GameGetTimeStr", &"GameGetTimeStrCustom",
	&"GameProcessTimeUntil", &"GameStartNextDay", &"GameAddLog", &"GameShowLog",
	&"GameIsDatapackLoaded",
	# Inventory
	&"InvAddItemID", &"InvAddXOfItemID", &"InvClearSlot", &"InvForceEquipItemID",
	&"InvGetItemIDCount", &"InvGetItemsWithTagCount", &"InvHasItemID",
	&"InvHasItemIDEquipped", &"InvHasItemsWithTag", &"InvHasSlotEquipped",
	&"InvHasXOfItemID", &"InvRemoveItemID", &"InvRemoveItemsWithTag",
	&"InvRemoveXOfItemID", &"InvResetInventory",
	# NPC
	&"NpcSetAtr", &"NpcGetPersStat", &"NpcSetPersStat", &"NpcAddPersStat",
	&"NpcGetFetish", &"NpcSetFetish", &"NpcHasBodypart", &"NpcSwitchBodypart",
	&"NpcRemBodypart", &"NpcGetBodypartID", &"NpcSetBreastSize", &"NpcSetPenisSize",
	&"NpcGetBodypatrAtr", &"NpcEncountersExclude", &"NpcEncountersInclude",
	&"NpcAddPCRep", &"NpcSetPCRepLvl", &"NpcGetPCRep",
	&"NpcAffectRelationship2", &"NpcGetRelationship2", &"NpcIsSpecies", &"NpcIsHybrid",
	# TF
	&"TFCanHas", &"TFStartTF", &"TFStartSpeciesTF", &"TFAccProg", &"TFProgress",
	&"TFIsUnlocked", &"TFDoUnlock", &"TFLabAccess", &"TFAddFluid", &"TFGetFluid",
	# Variables
	&"VarGet", &"VarSet", &"VarSetStr", &"VarSetBool", &"VarInc",
	&"VarIsNull", &"VarIsBool", &"VarIsNumber", &"VarIsString",
	&"RawString", &"RawInt", &"VarLocationName",
	# Flags
	&"FlagGet", &"FlagSet", &"FlagSetStr", &"FlagSetBool", &"FlagInc",
	&"FlagGlobGet", &"FlagGlobSet", &"FlagGlobSetStr", &"FlagGlobSetBool",
	&"FlagGlobInc", &"FlagGlobHas",
	# Type conversion
	&"ToString", &"ToInt", &"ToFloat",
	# String
	&"StringConcat", &"StringLen", &"StringAt", &"StringSubstr",
	&"StringHas", &"StringReplace", &"StringToCase",
	# RNG
	&"RNGChance", &"RNGFloat", &"RNGInt",
]

## Transpiles a block graph into a complete GDScript string
func transpile(blocks: Dictionary, start_node_id: String, block_count: int = 0) -> String:
	var generated_code: String = HEADER % block_count
	var current_node_id: String = start_node_id
	var indent: String = "\t"

	while current_node_id != "" and blocks.has(current_node_id):
		var block: Dictionary = blocks[current_node_id]
		var block_type: String = block.get("type", "")

		var line := _generate_block_code(block)
		if line != "":
			generated_code += indent + line + "\n"

		# Safety injection for while loops (migrated from original concept)
		if block_type == "FlowWhile":
			generated_code += indent + "\tawait cc_wait_seconds(get_tree(), 0.01)\n"

		current_node_id = block.get("next_id", "")

	return generated_code

## Translates a single block into a code line
func _generate_block_code(block: Dictionary) -> String:
	var block_type: String = block.get("type", "")

	match block_type:
		# --- Flow control ---
		"FlowIf":
			var condition: String = _resolve_value(block.get("condition", ""))
			var then_code: String = block.get("then_id", "")
			return "if %s:" % condition

		"FlowIfElse":
			var condition: String = _resolve_value(block.get("condition", ""))
			return "if %s:" % condition

		"FlowWhile":
			var condition: String = _resolve_value(block.get("condition", ""))
			return "while %s:" % condition

		# --- Math ---
		"MathPlus":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "0"))
			return "(%s + %s)" % [a, b]

		"MathMinus":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "0"))
			return "(%s - %s)" % [a, b]

		"MathMult":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "0"))
			return "(%s * %s)" % [a, b]

		"MathDivide":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "1"))
			return "(%s / %s)" % [a, b]

		# --- Logic ---
		"LogicAnd":
			var a: String = _resolve_value(block.get("a", "false"))
			var b: String = _resolve_value(block.get("b", "false"))
			return "(%s and %s)" % [a, b]

		"LogicOr":
			var a: String = _resolve_value(block.get("a", "false"))
			var b: String = _resolve_value(block.get("b", "false"))
			return "(%s or %s)" % [a, b]

		"LogicNot":
			var a: String = _resolve_value(block.get("a", "false"))
			return "not %s" % a

		"MathLogicEquals":
			var a: String = _resolve_value(block.get("a", ""))
			var b: String = _resolve_value(block.get("b", ""))
			return "(%s == %s)" % [a, b]

		"MathLogicNotEquals":
			var a: String = _resolve_value(block.get("a", ""))
			var b: String = _resolve_value(block.get("b", ""))
			return "(%s != %s)" % [a, b]

		"MathLogicBiggerThan":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "0"))
			return "(%s > %s)" % [a, b]

		"MathLogicLessThan":
			var a: String = _resolve_value(block.get("a", "0"))
			var b: String = _resolve_value(block.get("b", "0"))
			return "(%s < %s)" % [a, b]

		# --- Scene ---
		"SceneOutput", "SceneSay":
			var text: String = _resolve_value(block.get("text", ""))
			return 'say(%s)' % text

		"SceneButton":
			var name_text: String = _resolve_value(block.get("name", ""))
			var desc: String = _resolve_value(block.get("desc", ""))
			return 'add_button(%s, %s, null, null, null)' % [name_text, desc]

		"ScenePlayAnim":
			var anim_id: String = _resolve_value(block.get("anim_id", ""))
			return 'play_anim(%s)' % anim_id

		"SceneSetLocName":
			var text: String = _resolve_value(block.get("text", ""))
			return 'set_loc_name(%s)' % text

		"SceneEndScene":
			return 'do_run_event()'

		# --- Variables ---
		"VarGet":
			var var_id: String = str(block.get("var_id", ""))
			return 'get_var("&%s")' % var_id

		"VarSet":
			var var_id: String = str(block.get("var_id", ""))
			var value: String = _resolve_value(block.get("value", "null"))
			return 'set_var("&%s", %s)' % [var_id, value]

		"VarInc":
			var var_id: String = str(block.get("var_id", ""))
			var amount: String = _resolve_value(block.get("amount", "1"))
			return 'set_var("&%s", get_var("&%s", 0) + %s)' % [var_id, var_id, amount]

		# --- Flags ---
		"FlagGet":
			var flag_id: String = str(block.get("flag_id", ""))
			return 'get_flag_raw("&%s")' % flag_id

		"FlagSet":
			var flag_id: String = str(block.get("flag_id", ""))
			var value: String = _resolve_value(block.get("value", "null"))
			return 'set_flag_raw("&%s", %s)' % [flag_id, value]

		"FlagGlobGet":
			var flag_id: String = str(block.get("flag_id", ""))
			return 'get_flag_raw("&%s")' % flag_id

		"FlagGlobSet":
			var flag_id: String = str(block.get("flag_id", ""))
			var value: String = _resolve_value(block.get("value", "null"))
			return 'set_flag_raw("&%s", %s)' % [flag_id, value]

		# --- Inventory ---
		"InvAddItemID":
			var char_id: String = _resolve_value(block.get("char_id", "&pc"))
			var item_id: String = str(block.get("item_id", ""))
			var amount: int = block.get("amount", 1)
			return 'inv_add_item(%s, "&%s", %d)' % [char_id, item_id, amount]

		"InvRemoveItemID":
			var char_id: String = _resolve_value(block.get("char_id", "&pc"))
			var item_id: String = str(block.get("item_id", ""))
			var amount: int = block.get("amount", 1)
			return 'inv_remove_item(%s, "&%s", %d)' % [char_id, item_id, amount]

		"InvHasItemID":
			var char_id: String = _resolve_value(block.get("char_id", "&pc"))
			var item_id: String = str(block.get("item_id", ""))
			return 'inv_has_item(%s, "&%s")' % [char_id, item_id]

		# --- Character ---
		"GameAddAtr":
			var char_id: String = _resolve_value(block.get("char_id", "&pc"))
			var amount: int = block.get("amount", 1)
			return 'add_pain(%s, %d)' % [char_id, amount]

		# --- RNG ---
		"RNGChance":
			var chance: String = _resolve_value(block.get("chance", "50"))
			return 'RNG.chance(%s)' % chance

		"RNGInt":
			var min_val: String = _resolve_value(block.get("min", "0"))
			var max_val: String = _resolve_value(block.get("max", "100"))
			return 'randi_range(%s, %s)' % [min_val, max_val]

		# --- Type conversion ---
		"ToString":
			var value: String = _resolve_value(block.get("value", ""))
			return 'str(%s)' % value

		"ToInt":
			var value: String = _resolve_value(block.get("value", "0"))
			return 'int(%s)' % value

		"ToFloat":
			var value: String = _resolve_value(block.get("value", "0"))
			return 'float(%s)' % value

		# --- String ---
		"StringConcat":
			var a: String = _resolve_value(block.get("a", '""'))
			var b: String = _resolve_value(block.get("b", '""'))
			return '(%s + %s)' % [a, b]

		# --- Print (debug) ---
		"Print":
			var text: String = _resolve_value(block.get("text", ""))
			return 'cc_print(%s)' % text

		_:
			return "# Unknown block type: %s" % block_type

## Resolves a value reference (could be a literal, variable, or nested block)
func _resolve_value(value: Variant) -> String:
	if value is String:
		if value.begins_with("&"):
			return value  # StringName literal
		if value.begins_with("\""):
			return value  # String literal
		# Try to parse as number
		if value.is_valid_int():
			return value
		if value.is_valid_float():
			return value
		# Variable reference
		return 'get_var("&%s")' % value
	return str(value)
