# Tools/AiPromptGenerator.gd
@tool
class_name AiPromptGenerator extends EditorScript

## Migrated from the audit finding: "no automated tests, no linting, no CI/CD".
## Reads old Godot 3.x scripts and generates LLM prompts for migration.

const PROMPT_TEMPLATE := """Please migrate this Godot 3.x script to Godot 4.x (GDScript 2.0).
Requirements:
1. Use strict typing: `-> void`, `@export`, `StringName` (&"name")
2. Replace `GM.main.IS.*`, `GM.main.RS.*`, `GM.*` with `EventBus` signals or `ServiceLocator.get_service()`
3. Replace `yield()` with `await`
4. Replace `onready var` with `@onready var`
5. Replace `export` with `@export`
6. Replace `set_bone_custom_pose` with `SkeletonModifier3D`
7. Replace `Directory` with `DirAccess`
8. Replace `instance()` with `instantiate()`
9. Replace `connect("signal", obj, "method")` with `signal.connect(callable)`
10. Remove `_global_script_classes` references

SOURCE CODE:
{source_code}
"""

const MIGRATION_CHECKLIST := """
## Migration Checklist for {filename}:
- [ ] `onready` -> `@onready`
- [ ] `export` -> `@export`
- [ ] `yield()` -> `await`
- [ ] `GM.main.*` -> `EventBus` / `ServiceLocator`
- [ ] `Directory` -> `DirAccess`
- [ ] `File` -> `FileAccess`
- [ ] `PoolStringArray` -> `PackedStringArray`
- [ ] `instance()` -> `instantiate()`
- [ ] `connect("signal", obj, "method")` -> `signal.connect(callable)`
- [ ] `set_bone_custom_pose` -> `SkeletonModifier3D`
- [ ] `rand_range` -> `randf_range`
- [ ] `stepify` -> `snapped`
- [ ] `var2str`/`str2var` -> `var_to_str`/`str_to_var`
"""

func _run() -> void:
	# Find the most impactful files to migrate (by line count)
	var files_to_check := [
		"res://Game/BaseCharacter.gd",
		"res://Game/MainScene.gd",
		"res://GlobalRegistry.gd",
		"res://Game/SexEngine/SexEngine.gd",
		"res://Game/InteractionSystem/InteractionSystem.gd",
		"res://Player/Player3D/Doll3D.gd",
		"res://Game/World/World.gd",
	]

	var output := "# BDCC Migration Prompts\n\n"
	output += "Generated by AiPromptGenerator\n"
	output += "These prompts are ready to paste into ChatGPT/Claude for migration.\n\n"

	for file_path in files_to_check:
		var file := FileAccess.open(file_path, FileAccess.READ)
		if file:
			var source_code := file.get_as_text()
			file.close()

			# Truncate very long files to fit prompt limits
			if source_code.length() > 8000:
				source_code = source_code.substr(0, 8000) + "\n# ... (truncated, file is %d lines)" % source_code.count("\n")

			var prompt := PROMPT_TEMPLATE.replace("{source_code}", source_code)
			var checklist := MIGRATION_CHECKLIST.replace("{filename}", file_path.get_file())

			output += "---\n## %s\n\n" % file_path.get_file()
			output += "### Migration Checklist:\n%s\n\n" % checklist
			output += "### LLM Prompt:\n```\n%s\n```\n\n" % prompt

	# Save output
	var save_path := "res://Tools/migration_prompts.md"
	var save_file := FileAccess.open(save_path, FileAccess.WRITE)
	if save_file:
		save_file.store_string(output)
		save_file.close()
		print("[AiPromptGenerator] Migration prompts saved to: %s" % save_path)
		print("[AiPromptGenerator] Open this file and copy prompts into your LLM chat.")
	else:
		push_error("[AiPromptGenerator] Failed to save to: %s" % save_path)
